### ISSUE TITLE
Banner to unlock publishing still shows up once account has been unlocked

### ISSUE THREAD

**Issue by anikbrazeau** [cds-snc/platform-forms-client#4099] opened 2024-07-30 13:37 UTC
## Description
After creating an account and going through the steps of unlocking publishing and having that approved by Support, the banner with a CTA to unlock publishing still appears on the "Publish" page.

## Steps to reproduce
1. Go to GC Forms Staging
2. Create an account
3. Skip unlock publishing step
4. Create a form
5. Go to Publishing page
6. Unlock publishing 
7. Wait for support to approve the request
8. Go to Profile
9. See that publishing ability is unlocked
10. Go back to Publishing page
11. See that the banner still appears

## Details
- **Browser**: Edge
- **Operating system**: Tablet
- **Environment**: Staging
- **Language**: EN + FR
- **Viewport**: Tablet

## Expected behaviour
Once publishing is unlocked all indications or nudges to unlock should not appear

## Screenshots or videos

![unlocked](https://github.com/user-attachments/assets/7e97abb7-f9cd-48d3-a38e-456fb2783741)

![unlocked 2](https://github.com/user-attachments/assets/9056b43b-9e7a-4f9e-84be-0cebc34e5635)

**Comment by Abi-Nada** [comment] 2024-07-30 15:03
Re-tested and confirmed that the issue persists on my end too. This would block any new user who skipped publishing from being able to publish forms going forward.

**Comment by dsamojlenko** [comment] 2024-07-30 17:53
This is just a page cache issue.
If you simply hit the browser reload or CMD-R on the publish page after the permissions update, the screen updates.
I don't think we can revalidate that path programmatically when updating the permission, as we don't know the form ID when granting the permission.

**Comment by Abi-Nada** [comment] 2024-07-30 17:59
I've validated that I am able to publish after logging back in - closing this issue as it's not a bug

**Closed by Abi-Nada** 2024-07-30 17:59 UTC
Labels: bug, :vertical_traffic_light: Critical, App
