### ISSUE TITLE
Dashboard layout of a single form slightly different

### ISSUE THREAD

**Issue by wmoussa-gc** [cds-snc/platform-forms-client#3188] opened 2024-01-30 15:53 UTC
## Expected behaviour

<img width="1161" alt="image" src="https://github.com/cds-snc/platform-forms-client/assets/70960477/7f22e14c-5625-4e54-ad52-f2b30fa3d0fa">

## Screenshots or videos

<img width="1160" alt="image" src="https://github.com/cds-snc/platform-forms-client/assets/70960477/75e32b05-f476-47a9-b83b-138f72ff5a7b">

**Comment by anikbrazeau** [comment] 2024-01-30 15:58
Related to #3168

**Comment by craigzour** [comment] 2024-02-01 17:20
Duplicate of https://github.com/cds-snc/platform-forms-client/issues/3168

**Closed by craigzour** 2024-02-01 17:20 UTC
Labels: bug, app router
