### ISSUE TITLE
AddressComplete: Form filler entering address on mobile

### ISSUE THREAD

**Issue by anikbrazeau** [cds-snc/platform-forms-client#4612] opened 2024-11-06 17:07 UTC
## Description
The "Type to search" text cuts off on mobile

## Steps to reproduce
1. Fill out a form with AddressComplete component on mobile

## Details
- **Browser**: Safari
- **Operating system**: iOS
- **Environment**: Staging
- **Language**: EN/FR
- **Viewport**: Mobile
- **Output**: https://forms-staging.cdssandbox.xyz/en/id/cm35vgbuo000113ka5bzvgv0t

## Expected behaviour
Ability to see entire instruction
Responsiveness

## Screenshots or videos
<img width="369" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeU9kQnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--2084a68e5542dd56523ba578a9fdefbdd413ae85/cutoff.jpg" alt="cutoff.jpg" />

**Comment by ShadeWyrm** [comment] 2024-11-06 18:29
How would / should we fix this? @anikbrazeau

**Comment by ShadeWyrm** [comment] 2024-11-06 18:59
Duplicate of #4605

**Closed by ShadeWyrm** 2024-11-06 18:59 UTC
Labels: bug, App
