### ISSUE TITLE
Repeating set: bug: Page text displaying as markdown in right panel

### ISSUE THREAD

**Issue by connorscarolyns** [cds-snc/platform-forms-client#4356] opened 2024-10-04 12:49 UTC
## Description
A clear and concise description of what the problem is.
When I added the address preset element, the page text element showed as markdown in the panel view and was not clickable.

## Steps to reproduce
1. Go to 'repeating set, add modal'
2. Click on 'add address'
3. Open right panel
4. See the "what is your address" title displaying in markdown

## Details
- **Browser**: (chrom)
- **Operating system**: (Mac)
- **Environment**: (staging)
- **Language**: (English)
- **Viewport**: (80%)
- **Output**: (form id: cm1fb05zo0000tu9hgkxf92je)

## Expected behaviour
A clear and concise description of what's expected instead.
- The text element should look like the other element, be clickable and draggable.

## Screenshots or videos
Visual proof to help explain the problem.

<img width="430" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBd1FqQnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--3ce5daad02d18a762926c0e9d7be2327e0591b67/image.png" alt="image.png" />

<img width="943" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBd2NqQnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--d241491fce4010c9509e7b0b9a5cc934239b9233/image.png" alt="image.png" />

## Additional context
Any other information about the problem here. 

Form Json:
[test-form-2024-10-04.txt](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeFVqQnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--be8e6574d1ea6a1a55fefe7bbb857610247649a3/test-form-2024-10-04.txt)

**Comment by Abi-Nada** [comment] 2024-10-07 12:15
Removing as a duplicate of [4177](https://app.zenhub.com/workspaces/gcforms-60cb8929764d71000e481cab/issues/gh/cds-snc/platform-forms-client/4177) - it's not related to Repeating Sets, it happens outside of the Set as well. So we'll remove it from this Epic and prioritize within our tech debt/bug rotation

**Closed by Abi-Nada** 2024-10-07 12:15 UTC
Labels: bug, App
