### ISSUE TITLE
Different header and top nav for "Profile" page

### ISSUE THREAD

**Issue by anikbrazeau** [cds-snc/platform-forms-client#3452] opened 2024-04-09 13:27 UTC
## Description
When signed in on GC Forms, the header/top nav changes when you go to "Your account" > "Profile"

## Steps to reproduce
1. Sign in
2. Click on "Forms"
3. Notice the header/top nav
3. Click on "Your account" > "Profile"
4. Notice different header/top nav

## Details
- **Browser**: Edge
- **Operating system**: Windows
- **Environment**: App router PR
- **Language**: French
- **Viewport**: Tablet 100%

## Expected behaviour
Consistency and predictability in the navigation and header when signed in. Perhaps mirroring more of the "Forms" layout.

## Screenshots or videos

![profile](https://github.com/cds-snc/platform-forms-client/assets/38330843/300484ef-c914-4018-8489-18de81feaf53)

![Forms](https://github.com/cds-snc/platform-forms-client/assets/38330843/f61972b9-8896-4b9d-8ecb-62540c3fb8d3)

**Comment by connorscarolyns** [comment] 2024-04-11 15:42
I believe this is expected. All account actions leverage the GoC header used in the signup flow.

**Comment by Abi-Nada** [comment] 2024-04-22 11:56
@connorscarolyns this behaviour doesn't persists in prod currently (see vid below) - just confirming that by design it should switch to the GoC header? (aka is there a bug here to fix or is this behaviour of switching headers what we want?)

[Private Zenhub Video](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBKzErQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--6c37f49a9a95727f6d21f56870e81407e70571fe/Screen%20Recording%202024-04-22%20at%207.54.26%E2%80%AFAM.mov)

**Comment by connorscarolyns** [comment] 2024-04-22 12:03
I don't think we need to go to the effort to change it, whatever is showing is ok. With that said, all pages that fall under the "account" section within the IA should use the GoC header. This includes sign in, sign up, password reset, security questions, request to publish ...

**Comment by Abi-Nada** [comment] 2024-06-24 19:42
Closing as this is expected behaviour

**Closed by Abi-Nada** 2024-06-24 19:42 UTC
