### ISSUE TITLE
Name your form link doesn't work as expected

### ISSUE THREAD

**Issue by connorscarolyns** [cds-snc/platform-forms-client#2135] opened 2023-05-19 14:18 UTC
The link to name your form under the share option does not shift focus over to the form file name.

**Comment by Abi-Nada** [comment] 2023-05-24 16:27
Closing as a duplicate of [#2115](https://github.com/cds-snc/platform-forms-client/issues/2115)

**Closed by Abi-Nada** 2023-05-24 16:27 UTC
Labels: bug
