### ISSUE TITLE
Delete form failing

### ISSUE THREAD

**Issue by connorscarolyns** [cds-snc/platform-forms-client#3576] opened 2024-05-08 16:08 UTC
## Description
Delete form failed from Forms page.

## Steps to reproduce
1. Go to 'Forms page'
2. Click on 'more, then delete form'

## Details
- **Browser**: Chrome
- **Operating system**: Mac
- **Environment**: Staging
- **Language**: English
- **Viewport**: desktop

## Expected behaviour
A toast should appear with a success message, and form should be removed from the forms list

## Screenshots or videos
<img width="1011" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeUxGQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--3fd677d0e33c26b7df870b207309f2b66b7d3031/image.png" alt="image.png" />

**Comment by timarney** [comment] 2024-05-09 12:40
Ref: https://github.com/cds-snc/platform-forms-client/issues/3424

@thiessenp-cds looks like the issue happens on staging

**Comment by thiessenp-cds** [comment] 2024-05-13 17:19
I can't seem to reproduce this error today. @connorscarolyns when you have a minute, could you try re-testing this?

**Comment by connorscarolyns** [comment] 2024-05-13 17:52
I re-tested it, and it seems to be working now.

**Comment by Abi-Nada** [comment] 2024-05-14 11:31
Closing as issue no longer persists :)

**Closed by Abi-Nada** 2024-05-14 11:31 UTC
Labels: bug, app router
