### ISSUE TITLE
Responses sent to vault instead of email inbox?

### ISSUE THREAD

**Issue by Abi-Nada** [cds-snc/platform-forms-client#1868] opened 2023-04-06 13:16 UTC
### Description

I changed the Response Delivery to "Email the Response to an inbox", hit Save, and then inputted my responses under "Test" - but it still saved to the Vault?

[Will recreate issue and provide a screenshot/video soon - it didn't let me screen record my tablet when I was doing the test on Chrome because of "security policy"]

**Comment by thiessenp-cds** [comment] 2023-04-06 14:51
The error is easy to reproduce. Locally (dev environment) updating a published form to send submissions to either the vault or email results in an error.

On the client I can see an error:
```
status: 500
statusText: "Internal Server Error"
"Can't update published form"
```

On the server, I tracked down the error to the below lines of code I think. It looks like a logic error to me where a request to update a template intentionally fails.

[formID.ts]
```
const templateCRUD = async ({
...
}) => {
  const formID = request.query.formID as string;
  switch (method) {
     ...
    case "PUT":
      if (formID && formConfig) {
        ...
      } else if (formID && sendResponsesToVault) {
        return await removeDeliveryOption(ability, formID);
      }
...
```


templates.ts
```
...
export async function removeDeliveryOption(
...
    // Prevent already published templates from being updated
    if (templateWithAssociatedUsers.formRecord.isPublished)
      throw new TemplateAlreadyPublishedError();
...
```

**Comment by Abi-Nada** [comment] 2023-04-06 15:42
Thanks for the context, Pete!

I actually may have interpreted that part of the test wrong? I actually tried to change the delivery method while my Form was still in **Draft**. So while it was still in a Draft state:

1. I first tried out the Vault response (by going to "Test", inputting answer to the questions, and then checking responses)
2. Then I changed it to the email delivery method, hit Save, and repeated inputting answers in the "Test" page and submitting

So the functionality between Draft and Published is the same (that you can't change the methods? Or at least test out both response methods while in Draft?)

**Comment by timarney** [comment] 2023-04-12 11:47
Moved to review / qa --- for re-test

**Comment by Abi-Nada** [comment] 2023-04-12 14:06
Still seems to send Test responses to the vault, though I have it selected to "Email Response"?

![Screen Shot 2023-04-12 at 10.04.02 AM.png](https://images.zenhubusercontent.com/62a20a7f24877d05c343bf75/29a1c424-d69a-405a-b4c3-7af4c67f80b6)

![Screen Shot 2023-04-12 at 10.04.21 AM.png](https://images.zenhubusercontent.com/62a20a7f24877d05c343bf75/f7767629-b739-43ad-8ad3-f9951a5cc013)

**Comment by timarney** [comment] 2023-04-12 14:24
I tested on staging and see the email has a value but ... the delivery ends up in the vault.  @Abi-Nada do you receive an email as well or it lands only in the vault.

@bryan-robitaille or @craigzour can you confirm the database record is working or not working correctly for this.

Locally I see the Templates table either has a delivery option as "empty"

<img width="900" alt="Screen Shot 2023-04-12 at 10 22 36 AM" src="https://user-images.githubusercontent.com/62242/231488022-218ce222-8999-40bb-a2ad-b007af07c925.png">

or it contains email etc...

<img width="900" alt="Screen Shot 2023-04-12 at 10 24 04 AM" src="https://user-images.githubusercontent.com/62242/231488239-135d2d01-88e8-499d-8de5-f0ea1dd522f9.png">

**Comment by Abi-Nada** [comment] 2023-04-12 14:32
@timarney I didn't receive an email! But I believe that's expected behaviour for a "Test" response for a Draft form? At least, the confirmation message had said "You will not receive a reply". But I just wasn't expecting it to still go to the Vault so wanted to flag

**Comment by bryan-robitaille** [comment] 2023-04-12 17:22
Fix is in PR https://github.com/cds-snc/forms-terraform/pull/360

**Closed as completed** 2023-04-12 17:29 UTC
Labels: bug, :vertical_traffic_light: Critical
