### ISSUE TITLE
Opening a form file does not import the file name

### ISSUE THREAD

**Issue by anikbrazeau** [cds-snc/platform-forms-client#3235] opened 2024-02-06 19:34 UTC
## Description
When opening a form file (JSON), the imported form remains unnamed.

## Steps to reproduce
1. Go to GC Forms `/form-builder`
2. Click on Open a form file
3. Upload a JSON form file
4. See "unnamed form file"

## Details
- **Browser**: Edge
- **Operating system**: Windows
- **Environment**: App router preview + Staging
- **Language**: English
- **Viewport**: Tablet

## Expected behaviour
Import all the same info/data including file name?

## Screenshots or videos
https://github.com/cds-snc/platform-forms-client/assets/38330843/46d316a0-bc07-4d9b-b111-68ab20d51549

**Comment by Abi-Nada** [comment] 2024-09-20 19:27
Closing as a duplicate of [4079](https://app.zenhub.com/workspaces/gcforms-60cb8929764d71000e481cab/issues/gh/cds-snc/platform-forms-client/4079)

**Closed by Abi-Nada** 2024-09-20 19:27 UTC
Labels: bug
