### ISSUE TITLE
Bug: Assertion failed when pressing "Return" on TextArea

### ISSUE THREAD

**Issue by jeberhardt** [cds-snc/platform-forms-client#684] opened 2022-03-16 15:21 UTC
The following assertion failure is happening in the the JavaScript Console in Chrome (Version 99.0.4844.51) on Mac OS 12.2.1.
This error happens in both dev and staging.

<img width="477" alt="Screen Shot 2022-03-16 at 10 43 36 AM" src="https://user-images.githubusercontent.com/77435/158624857-ec7f9592-2642-4b3c-9cb8-2c2d8bbbda39.png">

To replicate:
- Load any form that has a TextArea component to it. (for example: https://forms-staging.cdssandbox.xyz/id/25)
- With focus on the textarea, press the return key.
- The error will appear in the console.

**Comment by falila** [comment] 2022-03-31 17:53
I couldn't reproduce this issue in staging with this config:
Firefox  98.0  🤔

**Comment by bryan-robitaille** [comment] 2022-03-31 18:50
After googling what application 'onloadwff.js' is executed as it turns out to be associated with the Chrome LastPass extension.  The error does not happen in the scope of our application but instead LastPass attempting to verify text in the field.  Closing the issues as the scope of the error is not within our purview to fix.

**Closed by bryan-robitaille** 2022-03-31 18:50 UTC
Labels: :vertical_traffic_light: Minor, development
