### ISSUE TITLE
App router: Sign in flow - padding is large on the right side 

### ISSUE THREAD

**Issue by samsadasivan** [cds-snc/platform-forms-client#3164] opened 2024-01-29 18:57 UTC
Issue: 
The widget has some styling issue. 

![image](https://github.com/cds-snc/platform-forms-client/assets/70960477/eccc8285-97e9-48d2-9a88-df8773881c58)

**Comment by wmoussa-gc** [comment] 2024-01-31 03:08
image is not snowing up @samsadasivan

**Comment by samsadasivan** [comment] 2024-01-31 14:50
Oh weird, here ill post again <img width="1438" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeVFYQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--b5f7e5c72102ecc8a6c1a73b67394d6c76e4eb91/image.png" alt="image.png" />

**Comment by wmoussa-gc** [comment] 2024-01-31 17:01
Oh, it seems the image was not visible when viewing this issue on GitHub: https://github.com/cds-snc/platform-forms-client/issues/3164. I pasted the image differently in your first comment using GitHub directly, but it looks like from ZenHub, the image doesn't render in GitHub.

**Comment by timarney** [comment] 2024-02-02 13:50
Should be fixed via https://github.com/cds-snc/platform-forms-client/pull/2583/commits/72d7165783ac40d43439d807ea7b95cfaf0450c0

**Comment by timarney** [comment] 2024-02-02 14:00
Confirmed - going to close this.

**Closed by timarney** 2024-02-02 14:00 UTC
Labels: bug, app router
