### ISSUE TITLE
Italics not displaying as expected

### ISSUE THREAD

**Issue by anikbrazeau** [cds-snc/platform-forms-client#3195] opened 2024-01-30 20:55 UTC
## Description
Testing Italics in page text

## Steps to reproduce
1. Go to "Form description" block in "Edit" for a form
2. Enter paragraph text
3. Select some paragraph text and italicize
4. Go to "Test" 
5. Text shows up with asterisk surrounding it rather than italics style

## Details
- **Browser**: Chrome
- **Operating system**: Mac Sonoma
- **Environment**: PR App router
- **Language**: French
- **Viewport**: Desktop

## Expected behaviour
WYSIWYG from editor to preview

## Screenshots or videos
https://github.com/cds-snc/platform-forms-client/assets/38330843/b53d0af0-49fd-4746-b38c-be9fc289d0ba

**Comment by thiessenp-cds** [comment] 2024-02-05 14:06
Works for me. This may have been fixed in another PR. @anikbrazeau when you have a chance, are you able to reproduce this error?

**Comment by timarney** [comment] 2024-02-05 17:19
I can't re-produce this either

**Comment by timarney** [comment] 2024-02-05 19:08
Will close --- can re-open as needed.

**Closed by timarney** 2024-02-05 19:08 UTC
Labels: bug, app router, cannot reproduce
