### ISSUE TITLE
Deleting fails from "Forms" 

### ISSUE THREAD

**Issue by timarney** [cds-snc/platform-forms-client#3424] opened 2024-03-27 13:46 UTC
## Description
Deleting a form from "Forms" returns a 500 error

## Steps to reproduce
1. Create a new draft form -- give it a title + save (no responses) just start a new form
2. Click on Forms --- try to delete the form
3. See error

<img width="854" alt="Screenshot 2024-03-27 at 9 37 50 AM" src="https://github.com/cds-snc/platform-forms-client/assets/62242/019efd8d-b7ab-4af5-a18b-37037a9cae93">

**Comment by timarney** [comment] 2024-03-27 14:04
https://github.com/cds-snc/platform-forms-client/assets/62242/72073be9-2deb-4061-bc95-f080f168c752

**Comment by thiessenp-cds** [comment] 2024-04-03 19:35
@timarney are you able to see this error anymore? I think this may have been resolved in #3442

**Comment by thiessenp-cds** [comment] 2024-04-10 13:59
https://github.com/cds-snc/platform-forms-client/assets/107579368/b03b2f4b-85e8-471d-bc2a-3975a97457b6

I was able to reproduce the bug! It looks like there is an error first about unprocessed submissions and then the PR environment becomes unstable. I'm guessing it may be restarting or something..

**Comment by timarney** [comment] 2024-04-10 19:46
@thiessenp-cds I retested a bunch of times and now I can't reproduce the error.

Possibly something updated based on the base branch.

**Comment by thiessenp-cds** [comment] 2024-04-11 12:46
Thanks for the testing help. I retested this morning and the delete functionality is working. I suspect an infra change or similar has fixed this.

**Closed by thiessenp-cds** 2024-04-11 12:46 UTC
Labels: bug, app router, cannot reproduce
