### ISSUE TITLE
Nagware failure when processing responses associated to deleted forms

### ISSUE THREAD

**Issue by craigzour** [cds-snc/platform-forms-client#1978] opened 2023-04-24 13:41 UTC
The current scenario is: A user can delete a form without confirming their responses. Because there are unconfirmed responses the nagware still fires but is unable to associate an owner to the response.

I think we have two options:
1. Stop a user from deleting a form if they have unconfirmed responses
2. Warn a user when they delete a form that they will be unable to retrieve responses. Then, confirm and delete the response for them.

**Comment by samsadasivan** [comment] 2023-04-24 20:08
Next steps: Discipline input and review cc: @srtalbot @connorscarolyns @craigzour @timarney @sarahhobson

**Comment by timarney** [comment] 2023-04-25 11:21
> Stop a user from deleting a form if they have unconfirmed responses

@craigzour --- outside of stopping them at a UI level should we also handle this at the API level and handle the error inside the current UI?

--

@samsadasivan I think we should look at My Form as the `entry point` for deletions.  It's currently the only way to delete. 

The app doesn't match Figma at the moment --- in a previous iteration delete from my forms redirected to the settings page.  The code was later updated to handle deletes directly from my forms.  I haven't got back around to re-introducing deleting from the settings page.

The above does make me wonder if we need the forms management page under settings --- it's all duplicated actions from My Form .   My understanding was My Form was for forms management.

**Comment by craigzour** [comment] 2023-04-25 12:11
> > Stop a user from deleting a form if they have unconfirmed responses
> 
> @craigzour --- outside of stopping them at a UI level should we also handle this at the API level?
> 
> --
> 
> @samsadasivan I think we should look at My Form as the `entry point` for deletions. It's currently the only way to delete.
> 
> The app doesn't match Figma at the moment --- in a previous iteration delete from my forms redirected to the settings page. The code was later updated to handle deletes directly from my forms. I haven't got back around to re-introducing deleting from the settings page.
> 
> The above does make me wonder if we need the forms management page under settings --- it's all duplicated actions from My Form . My understanding was My Form was for forms management.

@timarney Yes I think we should double check at the REST API or `lib/templates.ts` API because we may want to allow users to delete forms using the API at some point in the future. Also if we ever introduce a bug at the UI level we will have a second barrier.

I can start working on that API check while you tackle the UI part.

**Comment by samsadasivan** [comment] 2023-04-25 12:18
@timarney that makes sense. If we need to add another spot to find a way to delete the form from user insights, we can revisit this, but I like the idea that the builder interface is for editing and downloading. Then All Forms is for Form Management. Separating the workflows will be helpful for future features. 

Ok, in this case, the modal blocking deleting is the best route for now. I know clicking to eventually get blocked isn't ideal, but I don't want to have a disabled line item either haha.

**Comment by samsadasivan** [comment] 2023-04-25 12:19
I can also find a way to show how many responses are available to be download within the card. Carolyn had mentioned this in the past

**Comment by connorscarolyns** [comment] 2023-04-25 12:23
> Ok, in this case, the modal blocking deleting is the best route for now. I know clicking to eventually get blocked isn't ideal, but I don't want to have a disabled line item either haha.

I think this is ok for now. Make sure the user can get where they need to go from the error modal so that they can recover quickly and easily.

**Comment by anikbrazeau** [comment] 2023-04-25 12:48
From a content perspective, since there are there multiple things people need to know/do as they're deleting, perhaps we could take them through each one step-by-step to reduce cognitive load? 

1. Save (or send?) a copy of the form.
2. Download any form responses received.
3. Confirm the receipt of downloaded responses.
4. Re-confirm the irreversible deletion of the form.

**Comment by samsadasivan** [comment] 2023-04-25 14:05
**UPDATE**: @anikbrazeau is working on the copy and translation for the modal

**Comment by anikbrazeau** [comment] 2023-04-25 18:31
## UPDATED BILINGUAL CONTENT

### [Alert](https://www.figma.com/file/89fRce4gmy64UIArSZoAM8/v3.-GC-Forms-(builder-and-vault)?node-id=167-33276&t=SIBzKVV4A9T9KCwq-4)

**EN**: 
`**Download and confirm all responses before deleting form.**`
`[Go to Responses](/responses/)`
**FR**: 
`**Télécharger et confirmer toutes les réponses avant de supprimer le formulaire.**`
`[Accéder aux réponses](/responses/)`
___

### [Modal](https://www.figma.com/file/89fRce4gmy64UIArSZoAM8/v3.-GC-Forms-(builder-and-vault)?node-id=174-35394&t=SIBzKVV4A9T9KCwq-4)

**EN**: 
`**Get responses before deleting form**
This form has been published and is receiving responses. You have new responses to download and confirm. 

**Before deleting this form:** 
1. Download all responses.
2. Confirm the receipt of downloaded responses.

[Go to Responses]`

**FR**: 
`**Retirer les réponses avant de supprimer le formulaire**
Ce formulaire est publié et reçoit des réponses. Vous avez des nouvelles réponses à télécharger et à confirmer. 

**Avant de supprimer ce formulaire :** 
1. Télécharger toutes les réponses.
2. Confirmer la réception des réponses téléchargées.

[Accéder aux réponses]`

___

<img width="1239" alt="Screenshot 2023-04-25 at 2 30 03 PM" src="https://user-images.githubusercontent.com/38330843/234369174-af03978d-bbbd-4392-99c7-f2fd44f3cd25.png">

<img width="1171" alt="Screenshot 2023-04-25 at 2 30 10 PM" src="https://user-images.githubusercontent.com/38330843/234369179-f20a1daa-f0ef-43bd-a9ea-ac5e4e1b5ffa.png">

<img width="886" alt="Screenshot 2023-04-25 at 2 29 44 PM" src="https://user-images.githubusercontent.com/38330843/234369183-515afb45-a34f-4adb-9c31-6912e1440954.png">

<img width="881" alt="Screenshot 2023-04-25 at 2 29 52 PM" src="https://user-images.githubusercontent.com/38330843/234369187-7869fbb7-6dd1-478b-88ae-0abd7b7aff33.png">

**Comment by samsadasivan** [comment] 2023-04-26 14:44
Just let Anik know that we aren't doing the /Settings route, so refer to the modal for now :)

**Comment by timarney** [comment] 2023-04-26 18:27
Next steps can we confirm we're moving forward with the Modal screens above

- Via My Form
- User presses delete
- We check for responses that haven't been downloaded
- If we find  responses that haven't been downloaded -- show the screen above else try the delete...

We'll still want a nice error message if the delete fails ... unlikely but I think it would be possible for a new response to come in after the form response check but before I press delete.

**Comment by anikbrazeau** [comment] 2023-04-27 13:14
I think we're good to move forward with the modal -- open to feedback if anything should change. 😃 

As for the trigger -- is it checking for responses that haven't been downloaded **and haven't been confirmed**?

As for an error message if delete fails, how about something like: 
**EN**:  The form could not be deleted. Ensure there are no new responses and try again.
**FR**: Le formulaire n'a pas pu être supprimé. Veuillez vous assurer qu'il n'y a pas de nouvelles réponses et réessayez.

cc: @samsadasivan

**Comment by samsadasivan** [comment] 2023-04-27 13:16
Yes - thats correct. I think in this case, the "toast" feature could work for the error.

**Comment by samsadasivan** [comment] 2023-04-27 13:17
Ahh that is a good use case to look out for - @anikbrazeau I think the message works in this case

**Comment by samsadasivan** [comment] 2023-04-27 13:55
We can also use this error component, to appear at the top: ![image.png](https://images.zenhubusercontent.com/611408c194b5030c28d18261/f3bdddea-b4d1-4d07-8ea6-83ef2c31c0f7) 

For awareness, we have four types of error components: 
- Page errors (404,500) 
- Toast 
- Red alert 
- In-line form error messages. 

In this case - we can use the red alert or the toast, but I agree - the toast can't disappear. For simplicity - lets move forward with the red alert component. Ill pop the FR and EN mocks here

**Comment by samsadasivan** [comment] 2023-04-27 13:58
![image.png](https://images.zenhubusercontent.com/611408c194b5030c28d18261/04edfa41-846f-4bb1-a00b-6edc36bafb67)

**Comment by craigzour** [comment] 2023-04-27 14:03
> ![image.png](https://camo.githubusercontent.com/0978edb72c9455c024b28f2ed80ce5f32f873f0d8a18b4b57e871fc858f2bb2a/68747470733a2f2f696d616765732e7a656e68756275736572636f6e74656e742e636f6d2f3631313430386331393462353033306332386431383236312f30346564666134312d383436662d346262312d613030622d366564633336626166623637)

If we do it this way. Would that mean that we can let the user press the delete button no matter what? Then depending on the API response we let the user know whether it succeeded or failed because unprocessed responses have to be dealt with.

cc @bryan-robitaille

**Comment by samsadasivan** [comment] 2023-04-27 14:18
:D No worries! It's good to clarify haha

**Comment by timarney** [comment] 2023-05-01 14:11
Update 

Modal (merged)
https://github.com/cds-snc/platform-forms-client/pull/1999


Toast message (**updated current to not auto close**)
https://github.com/cds-snc/platform-forms-client/pull/2009

Noting we'll need to look at updating error styling for toast messages in a future card as the current doesn't match Figma.  We can also look at using the above error inline but again we should look to do break that work into a new card as it's more of a `global` styling thing vs specific to this issue.

**Comment by samsadasivan** [comment] 2023-05-03 18:50
Closing the loop on this issue: 

- Toast functionality will appear at the top of the screen to let users know if they have are able to delete a form or not. 
- The option to delete will only exist in the "Your Forms" page/view and not in each in the /Settings pages of individual forms 
- Next steps: Apply icon+header+message alert styling to toasts in a different card, issue #2029

**Comment by samsadasivan** [comment] 2023-05-03 18:50
Closing this :)

**Closed by samsadasivan** 2023-05-03 18:50 UTC
Labels: bug, development, needs_discussion

**Comment by samsadasivan** [comment] 2023-05-03 18:52
FOR REFERENCE: For users who deleted their forms that had responses they didn't download, they will now get a 404 page. Context and decision referenced in issue #2023
