### ISSUE TITLE
Blank comments rendered in HTML.

### ISSUE THREAD

**Issue by jeberhardt** [cds-snc/platform-forms-client#883] opened 2022-07-19 18:08 UTC
On some forms, there are some extraneous empty comments that appear in the code as `<!-- -->`. They can be seen when inspecting the code in Chrome.

They have been seen in both `staging` and `production`.

It _may_ be related to the `publishingStatus` of a form. I did not see any of these empty comments on a form (`publishingStatus = false`), then set it to `true`, and started seeing the empty comments. Setting it back to `false` did not remove the empty comments though.

I've seen no comments on first load of a form, but when doing a reload or hard-reload of the page, I start seeing the empty comments.

This bug does not seem to produce any negative effects, other than the empty comments themselves.

**Comment by jeberhardt** [comment] 2022-08-25 17:38
One comment from the Github React repo suggests that this is done on purpose:
https://github.com/facebook/react/issues/14725#issuecomment-458960400

**Comment by bryan-robitaille** [comment] 2022-10-06 16:22
Closing as this is not a bug but a side effect of React Hydrate

**Closed as completed by bryan-robitaille** 2022-10-06 16:22 UTC
Labels: bug
