### ISSUE TITLE
AddressComplete: Alignment in HTML receipt

### ISSUE THREAD

**Issue by anikbrazeau** [cds-snc/platform-forms-client#4617] opened 2024-11-06 20:27 UTC
## Description
Left align the column data in the receipt of response

## Steps to reproduce
1. Go to GC Forms Staging > Create form with Addresses on different pages > Set to download
2. Fill out a test response
3. Download HTML + receipt
4. Scroll down through receipt file for misaligned data

## Details
- **Browser**: Chrome
- **Operating system**: Mac
- **Environment**: Staging
- **Language**: EN
- **Viewport**: Desktop

## Expected behaviour
Left aligned for scannability and consistency

## Screenshots or videos

<img width="1094" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBL3VlQnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--bac25c62f4f1f3a39b589a4aa2036c4408da177f/Screenshot%202024-11-06%20at%203.24.54%E2%80%AFPM.png" alt="Screenshot 2024-11-06 at 3.24.54 PM.png" />

**Comment by Abi-Nada** [comment] 2024-11-07 13:55
Closing as a duplicate of #2110 , outside of AddressComplete functionality

**Closed by Abi-Nada** 2024-11-07 13:55 UTC
Labels: bug, App
