### ISSUE TITLE
Confirmation Modal  - UX

### ISSUE THREAD

**Issue by bryan-robitaille** [cds-snc/platform-forms-client#2090] opened 2023-05-11 12:18 UTC
As a user after I copy and paste a confirmation code I don't expect to click on 'Confirm Receipt' twice.

![confirm_annoyance.gif](https://images.zenhubusercontent.com/60cb88ea0e362d8320f759f0/455d0f10-dec8-4675-b528-1a3036aa6fe6)

**Comment by Abi-Nada** [comment] 2023-06-07 14:13
Duplicate of Issue [#1873](https://app.zenhub.com/workspaces/gcforms-60cb8929764d71000e481cab/issues/gh/cds-snc/platform-forms-client/1873) , so will be closing this card.

**Closed by Abi-Nada** 2023-06-07 14:13 UTC
Labels: :vertical_traffic_light: Minor
