### ISSUE TITLE
Spacing issue on "Email response settings" page

### ISSUE THREAD

**Issue by anikbrazeau** [cds-snc/platform-forms-client#3174] opened 2024-01-29 20:35 UTC
## Description
Heading and button are glued together

## Steps to reproduce
1. Go to a draft form
2. Go to "Settings"
3. "Response delivery" > "Response delivery option" > "Receive responses by email"
4. Save changes
5. Go to "Responses"
6. See issue

## Details
- **Browser**: Chrome
- **Operating system**: Mac
- **Environment**: App Router PR
- **Language**: English and French
- **Viewport**: Desktop

## Expected behaviour
Expect different button placement

## Screenshots 
<img width="1617" alt="Screenshot 2024-01-29 at 3 30 15 PM" src="https://github.com/cds-snc/platform-forms-client/assets/38330843/2ec8e18d-b993-4235-b1f0-0cef6d072e27">

<img width="1615" alt="Screenshot 2024-01-29 at 3 31 23 PM" src="https://github.com/cds-snc/platform-forms-client/assets/38330843/987d8752-161e-4926-a5e9-e22ccbd19cfe">

**Comment by timarney** [comment] 2024-02-05 17:16
Going to take the app router tag off this as the issue exists on the current develop branch.  We can look to fix just not a bug for the app router branch itself.

**Comment by timarney** [comment] 2024-02-05 19:04
Closing --- fixed here

https://github.com/cds-snc/platform-forms-client/issues/3194#issuecomment-1927612602

**Closed by timarney** 2024-02-05 19:04 UTC
Labels: bug
