### ISSUE TITLE
Differentiate icons for "dropdown" and "searchable list" form elements

### ISSUE THREAD

**Issue by anikbrazeau** [cds-snc/platform-forms-client#3885] opened 2024-06-24 14:36 UTC
## Description
Same icon used for two different form elements:

- Dropdown
- Searchable list

To help people make a choice more easily, consider differentiating the icons.

## Screenshots

<img width="846" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBenVJQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--432e502cae717af7d6bcacd79e0506b7a2fadd05/Screenshot%202024-06-24%20at%2010.30.32%E2%80%AFAM.png" alt="Screenshot 2024-06-24 at 10.30.32 AM.png" />

**Comment by Abi-Nada** [comment] 2024-06-24 19:10
Closing as a duplicate of #[3405](https://app.zenhub.com/workspaces/gcforms-60cb8929764d71000e481cab/issues/gh/cds-snc/platform-forms-client/3405) :)

**Closed by Abi-Nada** 2024-06-24 19:10 UTC
