### ISSUE TITLE
Consistency in CSV Format Response Headings

### ISSUE THREAD

**Issue by anikbrazeau** [cds-snc/platform-forms-client#4145] opened 2024-07-31 20:44 UTC
## Description
Some EN and FR separated by line break, some by slash.

## Steps to reproduce
1. Publish multi-page branching form
2. Submit response
3. See differences in heading format bilingually

## Details
- **Browser**: Chrome
- **Operating system**: Mac
- **Environment**: Staging
- **Language**: French
- **Viewport**: Desktop

## Expected behaviour
Same heading format or structure throughout the CSV response file.

## Screenshots or videos

<img width="2000" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNE1qQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--5111067de1086be772141cfcca2e7e0774295a40/Screenshot%202024-07-31%20at%204.36.28%E2%80%AFPM.png" alt="Screenshot 2024-07-31 at 4.36.28 PM.png" />

## Additional context
Any other information about the problem here.

**Comment by Abi-Nada** [comment] 2024-11-13 01:01
Closing as a duplicate of #4101

**Closed by Abi-Nada** 2024-11-13 01:01 UTC
Labels: bug, :vertical_traffic_light: Minor, App
