### ISSUE TITLE
Creating a draft form automatically checks off "Confirmation message" even if it remains empty?

### ISSUE THREAD

**Issue by anikbrazeau** [cds-snc/platform-forms-client#4713] opened 2024-11-27 16:59 UTC
## Description
The required confirmation message gets checked off prematurely.

## Steps to reproduce
1. Go to Staging
2. Create a new form
3. Go to publish
4. See "Confirmation message" checked off even before content is added

## Details
- **Browser**: Chrome
- **Operating system**: Mac
- **Environment**: Staging
- **Language**: EN/FR
- **Viewport**: desktop

## Expected behaviour
If the default heading is enough of a confirmation, we might consider removing it from the publishing checklist?
If we also require a more detailed message, we might consider unchecking the box indicating that step is complete?

## Screenshots or videos
<img width="1101" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeXp1Qnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--50497d3c4c68cf1ba8bd2731e8109ef179656a91/Screenshot%202024-11-25%20at%209.47.05%E2%80%AFAM.png" alt="Screenshot 2024-11-25 at 9.47.05 AM.png" />

**Comment by Abi-Nada** [comment] 2024-11-28 00:39
Duplicate of #4425

**Closed by Abi-Nada** 2024-11-28 00:39 UTC
Labels: bug, App
