### ISSUE TITLE
App router: Essential elements (description, privacy, and confirmation) disappear and reappear

### ISSUE THREAD

**Issue by samsadasivan** [cds-snc/platform-forms-client#3158] opened 2024-01-29 16:42 UTC
**Issue:** 
When I add a:

- form description
- privacy statement
- confirmation message

That content isn't displayed in the Translation tab. When I navigate back to Questions tab, it disappears.

Weird thing: So the privacy statement and confirmation message completely disappear but the description makes it over to the Translation tab, and just disappears when you navigate back to Questions tab. 

[**Slack thread** ](https://gcdigital.slack.com/archives/C06FNT23KBR/p1706545010760159)

**Comment by samsadasivan** [comment] 2024-01-29 16:44
[Private Zenhub Video](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNXNKQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--b45e8b77116db611cabce2fec2d22c4002846cec/Screen%20Recording%202024-01-29%20at%2011.15.46%E2%80%AFAM.mov)

**Comment by thiessenp-cds** [comment] 2024-01-29 17:36
Looks like this is happening in the current staging environment/branch also

**Comment by timarney** [comment] 2024-01-29 17:44
@thiessenp-cds not seeing this on staging have a video?

**Comment by anikbrazeau** [comment] 2024-01-29 21:47
Possibly related to #3178

**Comment by anikbrazeau** [comment] 2024-01-30 15:59
Related to #3187

**Comment by dsamojlenko** [comment] 2024-01-30 18:57
Fixed here: https://github.com/cds-snc/platform-forms-client/pull/2583/commits/9df7acadc668ac2ab5a15b724501fd94e7247d4a

**Comment by dsamojlenko** [comment] 2024-01-31 18:09
This is related to the RichTextEditor state. 
The content for the editor is initially empty and the editor's initial state can only be called once, so when the content eventually updates, the editor remains empty.

Have tried a number of solutions to no avail so far:
- Tried preventing render until `content` has a value, but the problem is sometimes `content` doesn't have a value but the editor needs to appear.
- Tried forcing a re-render once `content` has a value (using a key prop on containing div), but the problem is you get a rerender when you enter text into a blank editor which removes focus, so after typing a single character you have to click back in to continue.
- Tried using Lexical editor.update() to update the state on changes to content but you end up in a similar situation where the markdown conversion that fires on update strips trailing spaces on each keypress making it difficult to create sentences.

Taking a break from this investigation to focus on something different for a while.

**Comment by timarney** [comment] 2024-02-01 19:29
@samsadasivan can you re-test this now 

I think it's related to https://github.com/cds-snc/platform-forms-client/pull/3218

**Comment by timarney** [comment] 2024-02-05 19:08
Closing --- can re-open as needed but not seeing this now.

**Closed by timarney** 2024-02-05 19:08 UTC
Labels: app router
