### ISSUE TITLE
Rules for deleted options persisted after deletion

### ISSUE THREAD

**Issue by connorscarolyns** [cds-snc/platform-forms-client#3969] opened 2024-07-08 15:56 UTC
User feedback from the Diary study suggests that a rule applied to an option existed after the option was deleted, resulting in the user having to delete and recreate rules.

> I created a yes/no radio button question and experimented with ways to make it work as intended. Once it was working I realized I only needed one radio button, one that a user would use to trigger a new picklist to show. I deleted the unnecessary radio button (could have kept it but ultimately an unnecessary click for the user). The radio button I kept was the one with the rules applied to it. Removing the other radio button broke the rules from functioning but the "edit rules" option was still visible and the correct rules showed when I clicked on "edit rules". Had to remove and re-enter rules again.

**Comment by Abi-Nada** [comment] 2024-08-01 15:11
Closing as a duplicate of #4113

**Closed by Abi-Nada** 2024-08-01 15:11 UTC
Labels: bug, App
