### ISSUE TITLE
Missing info message

### ISSUE THREAD

**Issue by connorscarolyns** [cds-snc/platform-forms-client#2136] opened 2023-05-19 14:23 UTC
There is a missing string of content on the Branding page:
![image.png](https://images.zenhubusercontent.com/620427f3846ebb620d78e582/be831d20-e6f3-49d0-98e5-d19cd4d1913a)

**Comment by anikbrazeau** [comment] 2023-05-19 14:29
Related to #2121

**Comment by Abi-Nada** [comment] 2023-05-24 16:25
^ Closing this card, as it's a duplicate of #[2121](https://github.com/cds-snc/platform-forms-client/issues/2121)

**Closed by Abi-Nada** 2023-05-24 16:25 UTC
Labels: bug, :vertical_traffic_light: Moderate, content
