### ISSUE TITLE
Test 1.10 failed Searchable list not appearing in translation screen

### ISSUE THREAD

**Issue by connorscarolyns** [cds-snc/platform-forms-client#3360] opened 2024-03-19 13:19 UTC
1. Click on "Translations" and input translations - Failed
2. Make a change to the questions in Translations - passed
3. Click back onto "Questions" and validate that the changes appear in the Form Builder by toggling the languages - passed

The input fields for the searchable do not appear in the translation page. 

- Navigated to edit screen question appears in both French and English
- Navigate to the preview screen question appears in both French and English
- Navigate to the translation screen, question number appears, but no inputs
- Refresh the page, inputs are still missing
- Add translation in the edit screeen
- Navigate to the preview screen - transition are present
- Navigate to the translation screen - inputs are still missing
 
[test-form-carolyn-2024-03-19 (1).json.zip](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBN1B3QXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--5e7ce535c1b4726e73674c9bb3ad6d9c5f306012/test-form-carolyn-2024-03-19%20%281%29.json.zip)

<img width="1341" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNnp3QXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--2410b3d7f77b6feb45801be5ba4b19c76811a518/image.png" alt="image.png" />

**Comment by dsamojlenko** [comment] 2024-03-19 17:13
This should be fixed now https://github.com/cds-snc/platform-forms-client/pull/2583/commits/17349db49114e0026333fe3b7eea13028e89b882

Note that with a "Searchable list" component (ie, with a custom searchable list) you will be able to edit the Question, Hint text, and Options, whereas a managed data list that uses the same component (ie, Departments) you will be able to edit the Question and Hint text, but not the Options since they are managed.

**Comment by Abi-Nada** [comment] 2024-04-23 12:54
@connorscarolyns can you re-test and confirm if the issue still persists?

**Comment by connorscarolyns** [comment] 2024-04-23 14:31
Looks good to me

**Comment by Abi-Nada** [comment] 2024-04-25 11:31
Confirmed issue no longer persists - closing out card

**Closed by Abi-Nada** 2024-04-25 11:31 UTC
Labels: bug
