### ISSUE TITLE
"More" button in Card displayed text "card.menu.more"

### ISSUE THREAD

**Issue by Abi-Nada** [cds-snc/platform-forms-client#3344] opened 2024-03-16 21:41 UTC
## Description
While toggling between tabs and waiting for the page to load, I noticed that at one point the "More" button displayed text that said "card.menu.more" instead of "More"

## Steps to reproduce
1. Go to "Forms" in the PR Environment
2. Toggle between the tabs All/Drafts/Published
3. At some point between toggling, this pops up

## Details
- **Browser**: Chrome
- **Operating system**: Mac
- **Environment**: PR
- **Language**: English

## Expected behaviour
<img width="294" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOC9uQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--eba4c35844323c35bd67f35d54739461abe91d62/Screenshot%202024-03-16%20at%205.40.07%E2%80%AFPM.png" alt="Screenshot 2024-03-16 at 5.40.07 PM.png" />

## Screenshots or videos
<img width="1388" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOURuQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--b3678bddc6aaa24414f3d309b672d0dd741b6523/Screenshot%202024-03-16%20at%205.24.46%E2%80%AFPM.png" alt="Screenshot 2024-03-16 at 5.24.46 PM.png" />

## Additional context
**Note: I tried recreating and can't seem to reproduce the issue!**

**Comment by thiessenp-cds** [comment] 2024-03-18 17:10
I can't reproduce this either. The issue may have been resolved with another commit. I'll close this ticket for now.

**Closed by thiessenp-cds** 2024-03-18 17:10 UTC
Labels: bug
