### ISSUE TITLE
Go back to "Sign in" when resetting password

### ISSUE THREAD

**Issue by anikbrazeau** [cds-snc/platform-forms-client#4104] opened 2024-07-30 14:18 UTC
## Description
Once you've entered your email to reset your password the CTA button says to go back to homepage. 

## Steps to reproduce
1. Go to GC Forms Staging
2. Click on Reset password
3. Enter email and continue
4. See message to check email and button to go to homepage

## Details
- **Browser**: Edge
- **Operating system**: Windows
- **Environment**: Staging
- **Language**: EN / FR
- **Viewport**: Tablet

## Expected behaviour

- Preferable destination might be to "Go back to Sign in" or "Retourner à Se connecter"? 
- Or no button at all if the next action is within the email message?

## Screenshot

![password](https://github.com/user-attachments/assets/26185ad6-d14b-46d1-a765-46f861b036ac)

**Comment by Abi-Nada** [comment] 2024-07-30 14:40
Closing as a duplicate of [3624](https://app.zenhub.com/workspaces/gcforms-60cb8929764d71000e481cab/issues/gh/cds-snc/platform-forms-client/3624) :)

**Closed by Abi-Nada** 2024-07-30 14:40 UTC
Labels: bug, App
