### ISSUE TITLE
Error for site owner: Invalid domain for site key

### ISSUE THREAD

**Issue by anikbrazeau** [cds-snc/platform-forms-client#3362] opened 2024-03-19 19:29 UTC
## Description
A Box with red text indicating an error appears in the bottom right of the screen. Error is in English on French screen.

## Steps to reproduce
1. Go to `/fr/form-builder` page with "Create a form"
2. Click on GC Forms logo
3. Scroll down to bottom of the page

## Details
- **Browser**: Edge
- **Operating system**: Windows
- **Environment**: QA testing PR
- **Language**: French
- **Viewport**: Tablet 

## Expected behaviour
No error? Or a useful error message in the language of the interface?

## Screenshots or videos
![error](https://github.com/cds-snc/platform-forms-client/assets/38330843/8af8863d-cc3c-4cf5-826b-5cdfd51d08d1)
![error2](https://github.com/cds-snc/platform-forms-client/assets/38330843/96ed5b29-8741-4c00-b4c5-359875e3e7d6)

**Comment by Abi-Nada** [comment] 2024-03-19 19:37
Closing as this is expected behaviour in the preview environment - same issue raised in [3348](https://app.zenhub.com/workspaces/gcforms-60cb8929764d71000e481cab/issues/gh/cds-snc/platform-forms-client/3348) :)

**Closed by Abi-Nada** 2024-03-19 19:37 UTC
Labels: bug

**Comment by wmoussa-gc** [comment] 2024-03-21 18:09
It’s because recaptcha is only supported on our production and staging domains.

**Comment by timarney** [comment] 2024-03-22 14:28
Now checking to see if the flag is on --- this removes the error given we're not using recaptcha on staging.

https://github.com/cds-snc/platform-forms-client/pull/3407
