### ISSUE TITLE
Font inconsistency throughout app [API v2 QA]

### ISSUE THREAD

**Issue by anikbrazeau** [cds-snc/platform-forms-client#4721] opened 2024-11-28 13:13 UTC
## Description
There are a bunch of fonts in use within the app and within published forms.
Looks like a mix of Arial, Lato, Noto. 

## Steps to reproduce
1. Go to Sign in
2. See different fonts within the fields
3. Go to add a form element
4. See different fonts within the preview

## Details
- **Browser**: Edge
- **Operating system**: Windows
- **Environment**: Staging
- **Language**: English
- **Viewport**: Tablet

## Expected behaviour
Consistent typography system.
Seems Arial is the one that is out of place here.

## Screenshots or videos

![fonts](https://github.com/user-attachments/assets/54be5d81-4bbd-4eee-a1a2-2f1fcf359908)
![font 2](https://github.com/user-attachments/assets/71a49b2d-9ecd-440c-853b-398c71a5a379)

## Additional context
#4395

**Comment by Abi-Nada** [comment] 2024-11-28 14:29
Closing as a duplicate of #4395

**Closed by Abi-Nada** 2024-11-28 14:29 UTC
Labels: bug, App
