### ISSUE TITLE
Conditionally showing fieldset that starts with "page text" says page text rather than the input

### ISSUE THREAD

**Issue by anikbrazeau** [cds-snc/platform-forms-client#3406] opened 2024-03-22 14:04 UTC
## Description
Currently all "page text" types show up as "page text" under the option that when selected shows that field/part. 

## Steps to reproduce
1. Go to "Create" or "Edit" a draft form
2. Click on "Add form element"
3. Add a "radio button" with 2 options: full name and individual names
4. Add "full name"
5. Add "individual names"
6. Add a rule to show full name when full name is selected
7. Add a rule to show individual names when individual names is selected
8. See what rules apply "Show: full name" and "Show: "Page text"

## Details
- **Browser**: Chrome
- **Operating system**: Mac
- **Environment**: App router PR
- **Language**: English
- **Viewport**: Desktop

## Expected behaviour

If the questions show the actual inputted text for the conditional rule (in dropdown and in the form element block) than the page text should be the same (maybe truncated?). 

Something like First name / middle name / last name could be treated as one question?

## Screenshots or videos

<img width="1236" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBemdDQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--217fccd5dbcdae98cc0b1c2b334d882eb22d7f6c/Screenshot%202024-03-22%20at%209.57.38%E2%80%AFAM.png" alt="Screenshot 2024-03-22 at 9.57.38 AM.png" />

<img width="749" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBemNDQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--7915c2d2d8be0a2497288cb482cc28eb23bc1f96/Screenshot%202024-03-22%20at%209.57.53%E2%80%AFAM.png" alt="Screenshot 2024-03-22 at 9.57.53 AM.png" />

<img width="1139" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBejRDQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--4eca459150cb310894f577b59ebff447a0fdec95/Screenshot%202024-03-22%20at%2010.07.09%E2%80%AFAM.png" alt="Screenshot 2024-03-22 at 10.07.09 AM.png" />

**Comment by timarney** [comment] 2024-03-22 14:17
For now this is by design

https://gcdigital.slack.com/archives/C0676D34GPR/p1706114203989789?thread_ts=1706111882.795569&cid=C0676D34GPR

**Comment by Abi-Nada** [comment] 2024-03-22 14:27
^ De-scoping from the app router fixes :)

**Comment by Abi-Nada** [comment] 2024-06-24 19:54
Closing issue, as this is by design ^

**Closed by Abi-Nada** 2024-06-24 19:54 UTC
Labels: bug
