### ISSUE TITLE
Some primary buttons are on right, some on left in modals

### ISSUE THREAD

**Issue by anikbrazeau** [cds-snc/platform-forms-client#2991] opened 2023-12-01 19:19 UTC
# Issue / opportunity

Consistency in placement of primary buttons in relation to secondary buttons.
Easiest fix might be to alter the "Report a problem with responses" modal

# Screenshots

<img width="1152" alt="Screenshot 2023-12-01 at 2 15 23 PM" src="https://github.com/cds-snc/platform-forms-client/assets/38330843/fe97ffcf-361a-4a5a-bcda-71bc37374cde">

<img width="1154" alt="Screenshot 2023-12-01 at 2 15 31 PM" src="https://github.com/cds-snc/platform-forms-client/assets/38330843/f121efc8-69da-4890-b446-4681683cf3ae">

<img width="1207" alt="Screenshot 2023-12-01 at 2 15 42 PM" src="https://github.com/cds-snc/platform-forms-client/assets/38330843/a2b767da-08e1-4bbf-91d4-199831d92b04">

**Comment by Abi-Nada** [comment] 2024-07-30 15:15
Closing as a duplicate of #4109

**Closed by Abi-Nada** 2024-07-30 15:15 UTC
Labels: enhancement
