### ISSUE TITLE
Language order flips on initial landing page

### ISSUE THREAD

**Issue by anikbrazeau** [cds-snc/platform-forms-client#3185] opened 2024-01-30 15:28 UTC
## Description
The order of English and French changes on initial landing page

## Steps to reproduce
1. Go to https://7b326hq3bwxyh2tym7gc23dwcm0tmzog.lambda-url.ca-central-1.on.aws/
2. Click on English or French 
3. Go back
4. Click the other language
5. See the order change

## Details
- **Browser**: Chrome
- **Operating system**: Mac
- **Environment**: App router PR Preview
- **Language**: English / French
- **Viewport**: Desktop

## Expected behaviour
Consistent homepage?

## Screenshots or videos

https://github.com/cds-snc/platform-forms-client/assets/38330843/e5f37c53-5eca-4b32-968b-2293ffe211cd

**Comment by thiessenp-cds** [comment] 2024-02-02 15:01
@connorscarolyns would you know if this is the expected behavior? (Whatever language you select(ed) shows as the first language on the homepage)

**Comment by thiessenp-cds** [comment] 2024-02-05 21:15
I had a quick chat with @connorscarolyns and it looks like the current behavior is as expected. If not, this would be a low effort change after the app router code is merged

**Closed by thiessenp-cds** 2024-02-05 21:15 UTC
Labels: bug, app router
