### ISSUE TITLE
Top nav: "Signed in as"

### ISSUE THREAD

**Issue by anikbrazeau** [cds-snc/platform-forms-client#3399] opened 2024-03-21 19:52 UTC
## Description
Sometimes "Signed in as...." appears, sometimes it doesn't?

Related: #3385 Top nav sometimes says "Forms" on right side and sometimes "All forms / Form file name" on left side depending on whether within a form or looking at all forms. Also missing French string for "All forms" 

## Steps to reproduce
1. Go to Forms
2. Go to a draft form
3. Go to Your account > Profile
4. Go to Create a form
5. Spot the differences in top nav

## Details
- **Browser**: Edge
- **Operating system**: Windows
- **Environment**: App router PR
- **Language**: French
- **Viewport**: tablet

## Expected behaviour
More predictable and consistent navigational experience standardized

## Screenshots or videos

![instance4](https://github.com/cds-snc/platform-forms-client/assets/38330843/5312caf0-621a-4053-ae84-31eed235f101)
![instance1](https://github.com/cds-snc/platform-forms-client/assets/38330843/7761c970-0057-4e5e-8616-4c3f00ba117e)
![instance2](https://github.com/cds-snc/platform-forms-client/assets/38330843/f82dc048-7b85-403d-9a50-0273d72c00cc)
![Uploading instance3.PNG…]()

**Comment by thiessenp-cds** [comment] 2024-03-25 13:50
For the `/profile` and `/setup-security-question` pages, they use a different header than the form-builder pages. So I think that is by design - is that right @connorscarolyns . But IMO I like the idea of consistency.

**Comment by connorscarolyns** [comment] 2024-03-25 13:53
@thiessenp-cds Nope. The email was left over from old admin pages and never removed. We're fine with removing it from all pages, and keep them consistent.

**Comment by thiessenp-cds** [comment] 2024-03-25 17:29
Resolved in related PR

**Closed by thiessenp-cds** 2024-03-25 17:29 UTC
Labels: bug
