### ISSUE TITLE
ID showing up instead of content

### ISSUE THREAD

**Issue by anikbrazeau** [cds-snc/platform-forms-client#4089] opened 2024-07-29 18:50 UTC
## Description
In the "Show/Hide" add a display rule modal, text is showing up as a translation ID rather than the corresponding content.

`logic.tryitout.button`

[Staging]

<img width="499" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOVlZQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--77726870a1ddf82a6eb6a2d9a64ed2cf4f19d256/Screenshot%202024-07-29%20at%202.48.37%E2%80%AFPM.png" alt="Screenshot 2024-07-29 at 2.48.37 PM.png" />

**Comment by Abi-Nada** [comment] 2024-07-30 01:06
Closing as a duplicate of #4090 (even though you logged this issue exactly 2 minutes before I did hehehe🤭🫣)

**Closed by Abi-Nada** 2024-07-30 01:06 UTC
Labels: bug
